### ISSUE TITLE
SignalR Service Resource - SystemData is causing issues

### ISSUE THREAD

**Issue by mbfrahry** [hashicorp/pandora#1096]
When trying to create a signalR Network ACL, we're using the Model from the `Get` call for SignalR Service Resource and modifying that struct. This is returning a [SystemData](https://github.com/hashicorp/pandora/blob/main/data/Pandora.Definitions.ResourceManager/SignalR/v2022_02_01/SignalR/Model-SignalRResource.cs#L39) struct that is messing with Update call. 
```
Code="InvalidResource" Message="The resource definition is invalid."
```

If we remove the `SystemData` struct, the resource has no problem updating.

The Azure sdk does not return SystemData for SignalR

**Comment by tombuildsstuff** [comment]
Fixed via https://github.com/hashicorp/go-azure-helpers/pull/139
