### ISSUE TITLE
Schema "Mixins" do not currently support child folders

### ISSUE THREAD

**Issue by jackofallops** [hashicorp/pandora#1151]
ctx - https://github.com/hashicorp/pandora/pull/1138/files#diff-4caec5430a3f04e5cd0cbed629b9076eda140b06cdacc11654cd0f9679a460c5R87
```go 
func findAndMergeLocalMixins(input *loads.Document, basePath string, baseFile string) (*loads.Document, error) {
	if len(strings.Split(baseFile, "/")) != 2 { // We only care about local files, not sub-folders
		return input, nil
	}
```

The mixins used for capturing models in referenced files currently do not support files outside the CWD. This may or may not be a problem for services such as `DataFactory`, this issue is to surface that this _may_ be a problem when that service (or other service that makes use of sub-directories for additional hierarchical data) when we include them.

**Comment by tombuildsstuff** [comment]
Consolidating this into https://github.com/hashicorp/pandora/issues/2551 since this is related to Data Factory
