### ISSUE TITLE
missing `resourceGroup` of `galleryimages`  in `compute@2022-01-03`

### ISSUE THREAD

**Issue by ziyeqf** [hashicorp/pandora#1364]
When I added `compute@2022-01-03` and test locally. I have found the property `ResourceGroupNameParameter` seems to be missing.

in the generated file `resource-manager/compute/2022-01-03/galleryimages/id_image.go`
```
// ID returns the formatted Image ID
func (id ImageId) ID() string {
	fmtString := "/subscriptions/%s/providers/Microsoft.Compute/locations/%s/sharedGalleries/%s/images/%s"
	return fmt.Sprintf(fmtString, id.SubscriptionId, id.Location, id.GalleryUniqueName, id.GalleryImageName)
}
```
it seems to be different from swagger https://github.com/Azure/azure-rest-api-specs/blob/a31c376ede1e91abc3ab476ae8e8d316e80541c0/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-01-03/gallery.json#L286

steps to reproduce
---
1. merge PR #1362 
2. generate Go SDK locally

**Comment by tombuildsstuff** [comment]
This is now fixed: https://github.com/hashicorp/go-azure-sdk/blob/c46cf334b3f8a1bf0891be7373f34ff22fdf084b/resource-manager/compute/2022-03-03/galleryimages/id_galleryimage.go#L23-L31
