### ISSUE TITLE
tools/importer-rest-api-specs: raise an error when two blocks with the same name and different models exist

### ISSUE THREAD

**Issue by tombuildsstuff** [hashicorp/pandora#1542]
Chatting with @catriona-m, when generating the Terraform Schema for a Resource (in `importer-rest-api-specs`) we should look to ensure that each of the block names is unique and/or referencing the same model. If this isn't the case we should raise an error for someone to dig into, since the schema may need updating.

In the case of `VirtualMachine`, the `boot_diagnostics` block is defined twice, once within `DiagnosticsProfile` and once within `VirtualMachineInstanceView` - leading to an eventual consistency issue when generating the documentation, however the `InstanceView` should be being removed.

Ultimately removing `instanceView` will fix that specific issue - however we should look to detect these conflicts when generating the Terraform Schema and raise an error (initially) and (in the future) look to workaround these with prefixing.

* https://github.com/hashicorp/pandora/blob/b1cd9871278dd815ad9263cb461de98d373bde3e/data/Pandora.Definitions.ResourceManager/Compute/v2021_11_01/VirtualMachines/Model-DiagnosticsProfile.cs#L18-L19
* https://github.com/hashicorp/pandora/blob/b1cd9871278dd815ad9263cb461de98d373bde3e/data/Pandora.Definitions.ResourceManager/Compute/v2021_11_01/VirtualMachines/Model-VirtualMachineInstanceView.cs#L22

**Comment by catriona-m** [comment]
fixed by #1562
