### ISSUE TITLE
`Microsoft.Kusto@2022-07-07` - missing function from generated SDK

### ISSUE THREAD

**Issue by liuwuliuyun** [hashicorp/pandora#1727]
`Microsoft.Kusto@2022-07-07` generated SDK misses certain required function for resource `azurerm_kusto_script`

missing functions: 

scripts.NewScriptID
scripts.ParseScriptID
scripts.ParseScriptIDInsensitively

scripts.Clients.[Get/Create/Update/Delete]

In short, the folder here https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/kusto/2022-07-07/scripts is not complete. In theory, it should contains id_script.go and related function in it.

As a result, we could not migrate this resource to Pandora SDK for now.

**Comment by tombuildsstuff** [comment]
@liuwuliuyun that's because it's not actually in API Version `2022-07-07` - unfortunately this is a composite Swagger which are pretty misleading. Digging into the Azure SDK this is _actually_ in API version `2022-02-01` - as such can you send a PR to import that version?

Thanks!

**Comment by liuwuliuyun** [comment]
@tombuildsstuff Thanks for the feedback, let me open a PR about this.

**Comment by liuwuliuyun** [comment]
Hi @tombuildsstuff after merging above PR, I still don't see the related function in [2022-02-01](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/kusto/2022-02-01/scripts) or [2022-07-07](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/kusto/2022-07-07/scripts).

**Comment by tombuildsstuff** [comment]
@liuwuliuyun thanks for letting us know, taking a look through it appears there's a Swagger data issue here which needed fixing too - I've opened #1743 which fixes that
