### ISSUE TITLE
Data Issue: API Management @ 2022-08-01

### ISSUE THREAD

**Issue by tombuildsstuff** [hashicorp/pandora#2236]
```
Error: -14T07:21:37.853Z [ERROR]      💥 Error: parsing Swagger files: parsing files in "../../../swagger/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2022-08-01": parsing definition: finding resources for tag "PortalConfig": finding nested items yet to be parsed: appending model: appending models: different model objects. First fields: map[termsOfService:{Required:false ReadOnly:false Sensitive:false JsonName:termsOfService Description:Terms of service settings. CustomFieldType:<nil> ObjectDefinition:0xc001287640}]. Second fields: map[termsOfService:{Required:false ReadOnly:false Sensitive:false JsonName:termsOfService Description: CustomFieldType:<nil> ObjectDefinition:0xc001287d80}]
1214
    run_validate_can_parse_data_test.go:75: error: parsing Swagger files: parsing files in "../../../swagger/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2022-08-01": parsing definition: finding resources for tag "PortalConfig": finding nested items yet to be parsed: appending model: appending models: different model objects. First fields: map[termsOfService:{Required:false ReadOnly:false Sensitive:false JsonName:termsOfService Description:Terms of service settings. CustomFieldType:<nil> ObjectDefinition:0xc001287640}]. Second fields: map[termsOfService:{Required:false ReadOnly:false Sensitive:false JsonName:termsOfService Description: CustomFieldType:<nil> ObjectDefinition:0xc001287d80}]
```

**Comment by xuzhang3** [comment]
@tombuildsstuff  I found another issue of the `API-diagnostic` resource ID, `ApiId` was missed in the ID 

ID in Swagger: `"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/apis/{apiId}/diagnostics/{diagnosticId}"`(https://github.com/Azure/azure-rest-api-specs/blob/main/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json#L2444)

ID in SDK : `"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/diagnostics/{diagnosticId}"`
 
``

**Comment by tombuildsstuff** [comment]
@xuzhang3 this looks fine in `2021-08-01` now fwiw: https://github.com/hashicorp/go-azure-sdk/blob/main/resource-manager/apimanagement/2021-08-01/apidiagnostic/id_apidiagnostic.go#L121

Mind taking another look at this one?

**Comment by tombuildsstuff** [comment]
Looks like `2022-08-01` also imports fine now fwiw - so I think this issue can be closed / we can import that version

**Comment by xuzhang3** [comment]
@tombuildsstuff thanks for your wok. . Now I'm working on migrating APIM SDK to pandora, everything is working fine so far.
