### ISSUE TITLE
Workloads.sapvirtualinstances.NewSAPVirtualInstancesClientWithBaseURI func is different with others

### ISSUE THREAD

**Issue by neil-yechenwei** [hashicorp/pandora#2275]
While I am integrating with [Workloads](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/workloads/2023-04-01) RP, the Workloads.sapvirtualinstances.[NewSAPVirtualInstancesClientWithBaseURI](https://github.com/hashicorp/go-azure-sdk/blob/9f74cb7516777648ca69bf0a88a8f818dd98c4d6/resource-manager/workloads/2023-04-01/sapvirtualinstances/client.go#L17) func always returns error. Then I checked the func definition. Seems it's different with others. Could you take a look this issue? Thanks.

![image](https://user-images.githubusercontent.com/19754191/227833950-948b8e4d-494f-47e0-a2bd-cebd1a2240ea.png)

1. There are two return values in NewSAPVirtualInstancesClientWithBaseURI but other RPs only return one value.
2. NewSAPVirtualInstancesClientWithBaseURI doesn't accept the input parameter endpoint. It's also different with others.
3. The type of "sapVirtualInstancesClient.Client" is different with what the "o.ConfigureClient" func requires.

**Comment by wuxu92** [comment]
you can init the Client of using the New Base Layer like this: https://github.com/hashicorp/terraform-provider-azurerm/blob/ff705d53fc7d50a1ab0de268c1c6fa2bf819b16b/internal/services/dns/client/client.go#L10

**Comment by neil-yechenwei** [comment]
Sure. Thanks. It works fine now.

```
import (
	sapvirtualinstances_v2023_04_01 "github.com/hashicorp/go-azure-sdk/resource-manager/workloads/2023-04-01"
	"github.com/hashicorp/go-azure-sdk/sdk/client/resourcemanager"
	"github.com/hashicorp/terraform-provider-azurerm/internal/common"
)

func NewClient(o *common.ClientOptions) (*sapvirtualinstances_v2023_04_01.Client, error) {
	client, err := sapvirtualinstances_v2023_04_01.NewClientWithBaseURI(o.Environment.ResourceManager, func(c *resourcemanager.Client) {
		o.Configure(c, o.Authorizers.ResourceManager)
	})
	if err != nil {
		return nil, err
	}
	return client, nil
}
```
