### ISSUE TITLE
Data Issue: Data Factory uses a different directory structure for the Swagger files

### ISSUE THREAD

**Issue by katbyte** [hashicorp/pandora#2551]
Data Factory exposes the Discriminated Implementations within a sub-directory/different files to the interface, so we're missing implementations in the output:

![image](https://github.com/hashicorp/pandora/assets/666005/4d98ae31-d9c0-4108-abd8-33f2002d115f)

![image](https://github.com/hashicorp/pandora/assets/1638467/f7d9ced4-fcf8-439a-8a2d-1a84d25595a7)

As such we're gonna need to check all of the Swagger files for all implementations of an interface, rather than the swagger file where the interface is, which isn't going to be fast but should work

**Comment by stephybun** [comment]
Closed by #3727
