### ISSUE TITLE
BotChannelEmail - the values for AuthMethod should be surfaced correctly as constants in Pandora.

### ISSUE THREAD

**Issue by neil-yechenwei** [hashicorp/pandora#3254]
The values for AuthMethod in BotChannelEmail should be surfaced correctly as constants in Pandora. See more details from https://github.com/Azure/azure-rest-api-specs/blob/80c21c17b4a7aa57f637ee594f7cfd653255a7e0/specification/botservice/resource-manager/Microsoft.BotService/stable/2022-09-15/botservice.json#L2194. Per the suggestion from https://github.com/hashicorp/terraform-provider-azurerm/pull/23129#issuecomment-1720716075, I filed this issue for tracking.

**Comment by tombuildsstuff** [comment]
This is tracked in https://github.com/hashicorp/pandora/issues/3010 - closing this issue in favour of that issue.
