### ISSUE TITLE
`generator-terraform`: issues when generating `ChaosStudio`

### ISSUE THREAD

**Issue by wuxu92** [hashicorp/pandora#3261]
I am generating ChaosStudio resources by the `gnerator-terraform` tool, but there are two issues blocked my way:

1. Seems the generator cannot handle the scope segment in the reosurce ID? The resource id of [targets ](https://github.com/Azure/azure-rest-api-specs/blob/13ef12f5de907f32bb6cac13123824c48c911411/specification/chaos/resource-manager/Microsoft.Chaos/stable/2023-11-01/targets.json#L91C108-L91C151) and [capability ](https://github.com/Azure/azure-rest-api-specs/blob/13ef12f5de907f32bb6cac13123824c48c911411/specification/chaos/resource-manager/Microsoft.Chaos/stable/2023-11-01/capabilities.json#L94C84-L94C149) resource are parsed as scopeSegment but then filtered out by [this logic](https://github.com/hashicorp/pandora/blob/8042bd6761569b0104b53f9a7041674e0154e290/tools/importer-rest-api-specs/components/resources/identification.go#L24-L26). So the importer tool cannot generate the Terraform part correctly.

2. The `Experiments` resource can be generated but go build with errors ilke below:

```
./experiment_resource_gen.go:370:20: cannot use identity (variable of type *[]identity.ModelSystemAssignedUserAssigned) as []identity.ModelSystemAssignedUserAssigned value in assignment
./experiment_resource_gen.go:434:15: r.mapChaosStudioExperimentResourceFilterSchemaToSelector undefined (type ChaosStudioExperimentResource has no field or method mapChaosStudioExperimentResourceFilterSchemaToSelector)
./experiment_resource_gen.go:445:14: r.mapSelectorToChaosStudioExperimentResourceFilterSchema undefined (type ChaosStudioExperimentResource has no field or method mapSelectorToChaosStudioExperimentResourceFilterSchema)
```

**Comment by tombuildsstuff** [comment]
@wuxu92 the board you've assigned this for is for tracking issues with the API Definitions - I'm going to remove it from that board because this doesn't appear to be an issue with the API Definitions?

**Comment by wuxu92** [comment]
@tombuildsstuff I am sorry, I misunderstood the usage of the dashboard. Please go ahead and  remove it.

**Comment by stephybun** [comment]
Support for all Chaos Studio resources was added in February and scoped resources can now be generated with Pandora. 

Experiments being a more intricate resource with arrays and nested fields is not currently considered for generation with Pandora at this point in time. 

As such I'm going to close this issue since this has been completed by the following PRs https://github.com/hashicorp/pandora/pull/3671 https://github.com/hashicorp/pandora/pull/3586 https://github.com/hashicorp/terraform-provider-azurerm/pull/24779
