### ISSUE TITLE
Documentation: Object Definitions

### ISSUE THREAD

**Issue by stephybun** [hashicorp/pandora#3439]

**Comment by tombuildsstuff** [comment]
In the end we ended up deciding to document these inline within the new SDK types, so I'm going to close this out:

* [SDK Object Definition](https://github.com/hashicorp/pandora/blob/main/tools/data-api-sdk/v1/models/sdk_object_definition.go) (there's an associated `SDK Object Definition Type` too)
* [SDK Operation Option Object Definition](https://github.com/hashicorp/pandora/blob/main/tools/data-api-sdk/v1/models/sdk_operation_option_object_definition.go) (there's an associated `SDK Operation Option Object Definition Type` too)
* [Terraform Schema Object Definition](https://github.com/hashicorp/pandora/blob/main/tools/data-api-sdk/v1/models/terraform_schema_object_definition.go) (there's an associated `Terraform Schema Object Definition Type` too)
