### ISSUE TITLE
use common client options to configure clients 

### ISSUE THREAD

**Issue by ms-henglu** [hashicorp/pandora#3638]
There're some clients that the initialization doesn't use the common client option's configure methods. So these RP's resources don't support features like logging, user-agent, and correlation request id.

refs: https://github.com/hashicorp/pandora/blob/8d89fba5c90fc161c3fb9a6a48aa98a354321525/tools/generator-terraform/generator/definitions/template_service_client.go#L59

**Comment by ms-henglu** [comment]
https://github.com/hashicorp/terraform-provider-azurerm/pull/22387

**Comment by tombuildsstuff** [comment]
@ms-henglu thanks for reporting this - just so we can triage this one - were you planning to send a PR to fix this issue?

**Comment by ms-henglu** [comment]
Hi @tombuildsstuff , sorry, no.
