### ISSUE TITLE
`ChaosStudio` @ `2023-11-01` discriminator models aren't parsed in `Experiments`

### ISSUE THREAD

**Issue by stephybun** [hashicorp/pandora#3693]
Chaos Studio has several discriminated models that aren't being parsed and are missing in the API definitions

https://github.com/Azure/azure-rest-api-specs/blob/21a8d55d74e4425e96d76e5835f52cfc9eb95a22/specification/chaos/resource-manager/Microsoft.Chaos/stable/2023-11-01/types/experiments.json#L197-L294

https://github.com/Azure/azure-rest-api-specs/blob/21a8d55d74e4425e96d76e5835f52cfc9eb95a22/specification/chaos/resource-manager/Microsoft.Chaos/stable/2023-11-01/types/experiments.json#L330-L416

https://github.com/Azure/azure-rest-api-specs/blob/21a8d55d74e4425e96d76e5835f52cfc9eb95a22/specification/chaos/resource-manager/Microsoft.Chaos/stable/2023-11-01/types/experiments.json#L417-L468

Related to https://github.com/hashicorp/pandora/issues/2551

**Comment by tombuildsstuff** [comment]
Looks like another instance of https://github.com/hashicorp/pandora/issues/2551
