### ISSUE TITLE
`DataMigration` - Remove unused constants and models

### ISSUE THREAD

**Issue by stephybun** [hashicorp/pandora#3735]
#3727 introduced the ability to parse models/constants nested directories without any reference to a tag/operation/resource ID.

For Chaos Studio, Data Factory and potential other future RPs this is necessary, but it has output some unused constants/models for other RPs like DataMigration.

See the non-breaking changes for DataMigration in this comment:
https://github.com/hashicorp/pandora/pull/3734#issuecomment-1918898894

**Comment by tombuildsstuff** [comment]
`go-azure-sdk` PR containing the generated output: https://github.com/hashicorp/go-azure-sdk/pull/864

**Comment by tombuildsstuff** [comment]
Fixed in `main`
