### ISSUE TITLE
Azure REST API 2023-12-30

### ISSUE THREAD

**Issue by giotab** [hashicorp/pandora#4160]
Hi,

Not entirely sure about the process, but based on this https://github.com/hashicorp/go-azure-sdk/issues/912 , then this might be the place to request a new version of [Azure REST API for MySql](https://learn.microsoft.com/en-us/rest/api/mysql/flexibleserver/operation-groups?view=rest-mysql-flexibleserver-2023-12-30).
Current version in the [SDK](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/mysql) is 2022-01-1.
Requesting to update to 2023-12-30

**Comment by tombuildsstuff** [comment]
hey @giotab 

Thanks for opening this issue - this is the right place to request those, and as such I've opened https://github.com/hashicorp/pandora/pull/4166 which'll add support for this new API version. Once that's merged it'll generate a PR which'll eventually generate `hashicorp/go-azure-sdk` - I'll post a comment when that's available.

Thanks!

**Comment by tombuildsstuff** [comment]
Go SDK PR: https://github.com/hashicorp/go-azure-sdk/pull/1002 - will be releasing shortly
