### ISSUE TITLE
Chaos Studio Target ListComplete API always times out

### ISSUE THREAD

**Issue by neil-yechenwei** [hashicorp/pandora#4354]
Recently I found all test cases about Chaos Studio are failed on Teamcity. After I investigated, I found that [ListComplete API ](https://github.com/hashicorp/terraform-provider-azurerm/blob/1b6e07fc03daf3671216720cac603e4edb2c5d91/internal/services/chaosstudio/chaos_studio_target_resource_create.go#L35)generated by Pandora would always time out. I also tried [List azure rest api](https://learn.microsoft.com/en-us/rest/api/chaosstudio/target-types/list?view=rest-chaosstudio-2024-01-01&tabs=HTTP) and it works fine. This issue happens since 2024-07-01. I found there is a [change](https://github.com/hashicorp/terraform-provider-azurerm/pull/26502/files#diff-a724525ba34017d35664fbbedd0cca74e74a15a8991a13038f0844941113a9b0) on go-azure-sdk at 2024-07-01. This is the corresponding [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/26502). So I assume it's a regression issue on Pandora. Could you take a look at this issue? Thanks.

API version: 2023-11-01

Request payload:
```
GET https://management.azure.com/subscriptions/xx-xx-xx-xx/providers/Microsoft.Chaos/locations/westeurope/targetTypes
```
 
Error Message:
```
loading results: Get "": context deadline exceeded
```

This is the related issue : https://github.com/hashicorp/terraform-provider-azurerm/issues/27023

**Comment by thomas-shares** [comment]
We are impacted by this as we can't run our Chaos Studio tests any more from Terraform. Is there any outlook on this being picked up, and can I help in some way?

**Comment by rodmhgl** [comment]
Any updates, workarounds, or acknowledgements on this issue?

**Comment by neil-yechenwei** [comment]
This issue has gone and [new issue](https://github.com/hashicorp/pandora/issues/4535) has occurred. So I will close this issue.
